### Configurações Globais
@baseUrl = http://localhost:3000

# ### 1. Cadastrar um Curso
# POST {{baseUrl}}/cursos
# Content-Type: application/json

# {
#     "nome": "Análise e Desenvolvimento de Sistemas",
#     "carga_horaria": 2000,
#     "email_coordenacao": "ads@faculdade.com"
# }

# ### 2. Listar Cursos (para conferir o ID gerado)
# GET {{baseUrl}}/cursos

### 3. Cadastrar uma Empresa
# POST {{baseUrl}}/empresas
# Content-Type: application/json

# {
#     "CNPJ_NibocoProd": "12345678000199",
#     "nome_social": "Tech Solutions LTDA",
#     "nome_fantasia": "TechSol",
#     "endereco": "Rua das Flores, 123",
#     "telefone": "11999999999",
#     "email": "contato@techsol.com"
# }

# ### 4. Cadastrar um Aluno
# POST {{baseUrl}}/alunos
# Content-Type: application/json

# {
#     "matricula": 2024001,
#     "nome": "João Silva",
#     "cpf": "123.456.789-00",
#     "email": "joao@email.com",
#     "id_curso": 1
# }

### 5. Cadastrar um Orientador
# POST {{baseUrl}}/orientadores
# Content-Type: application/json

# {
#     "nome": "Prof. Ricardo Rocha",
#     "email": "ricardo@faculdade.com",
#     "telefone": "11988887777"
# }

# ### 6. Listar todos os Alunos
# GET {{baseUrl}}/alunos